import { Inter, DM_Sans, Epilogue } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const epilogue = Epilogue({ subsets: ["latin"], variable: "--epilogue" });
const inter = Inter({ subsets: ["latin"], variable: "--inter" });
const dm_sans = DM_Sans({ subsets: ["latin"], variable: "--dm_sans" });
const din_condensed = localFont({
   src: "../../public/fonts/D-DINCondensed.otf",
   variable: "--din_condensed",
});

// export const metadata: Metadata = {
//    title: "Create Next App",
//    description: "Generated by create next app",
// };

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="es">
         <link rel="icon" href="/favicon.ico" sizes="any" />
         <body
            className={cn(
               epilogue.variable,
               inter.variable,
               dm_sans.variable,
               din_condensed.variable,
               "font-inter sm:hidden",
            )}
         >
            {children}
         </body>
      </html>
   );
}
